name: iOS Build (Debug)
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Fastlane Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "26"
      - name: Install Prereqs
        run: |
          brew install swift-protobuf
          brew tap tuist/tuist
          brew install --formula tuist
      - name: Build Logic (Debug, iOS)
        run: make logic ALL_TARGETS="aarch64-apple-ios" MODE=debug
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: sccache
      - name: Generate Xcode Project
        run: tuist generate
        working-directory: app
      - name: Fastlane build
        run: fastlane build
        working-directory: app
